spring:
  application:
    name: userservice
  datasource:
    url: jdbc:h2:file:./localdata/h2db/userservice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  auth:
    types: basic,sso,jwt
  jwt:
    secret: verysecretchangemeverysecretchangeme
    enabled: true
    auth:
      algorithm: RS256   # or ES256
    expiration-seconds: 3600
    expiration-ms: 30000000
    rsa:
      privateKeyFile: classpath:key/private_key.pem
      publicKeyFile: classpath:key/public_key.pem
    

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

